// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fan.proto

package com.Fan;

public interface FanInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FanInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.FanInfo faninfo = 1;</code>
   */
  boolean hasFaninfo();
  /**
   * <code>.FanInfo faninfo = 1;</code>
   */
  com.Fan.FanInfo getFaninfo();
  /**
   * <code>.FanInfo faninfo = 1;</code>
   */
  com.Fan.FanInfoOrBuilder getFaninfoOrBuilder();
}
