// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fan.proto

package com.Fan;

public interface FanInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FanInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 device_id = 1;</code>
   */
  int getDeviceId();

  /**
   * <code>string location = 2;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 2;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>int32 speed = 3;</code>
   */
  int getSpeed();
}
