// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fan.proto

package com.Fan;

public interface GetDeviceByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetDeviceByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 device_id = 1;</code>
   */
  int getDeviceId();
}
