// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Fan.proto

package com.Fan;

public interface GetSpeedRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetSpeedRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 device_id = 1;</code>
   */
  int getDeviceId();

  /**
   * <code>int32 speed = 2;</code>
   */
  int getSpeed();
}
