// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heating.proto

package com.Heating;

public interface HeaterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Heater)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 device_id = 1;</code>
   */
  int getDeviceId();

  /**
   * <code>string location = 2;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 2;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string status = 3;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 3;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>int32 temperature = 4;</code>
   */
  int getTemperature();
}
