// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heating.proto

package com.Heating;

public interface HeaterInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeaterInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Heater heater = 1;</code>
   */
  boolean hasHeater();
  /**
   * <code>.Heater heater = 1;</code>
   */
  com.Heating.Heater getHeater();
  /**
   * <code>.Heater heater = 1;</code>
   */
  com.Heating.HeaterOrBuilder getHeaterOrBuilder();
}
