// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heating.proto

package com.Heating;

public final class Heating {
  private Heating() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Heater_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Heater_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeaterStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeaterStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeaterToUpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeaterToUpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeaterInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_HeaterInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rHeating.proto\"R\n\006Heater\022\021\n\tdevice_id\030\001" +
      " \001(\005\022\020\n\010location\030\002 \001(\t\022\016\n\006status\030\003 \001(\t\022\023" +
      "\n\013temperature\030\004 \001(\005\"(\n\023HeaterStatusReque" +
      "st\022\021\n\tdevice_id\030\001 \001(\005\"8\n\025HeaterToUpdateR" +
      "equest\022\021\n\tdevice_id\030\001 \001(\005\022\014\n\004temp\030\002 \001(\005\"" +
      "-\n\022HeaterInfoResponse\022\027\n\006heater\030\001 \001(\0132\007." +
      "Heater2\277\001\n\016HeatingService\0229\n\nShowStatus\022" +
      "\024.HeaterStatusRequest\032\023.HeaterInfoRespon" +
      "se\"\000\0228\n\007SetTemp\022\026.HeaterToUpdateRequest\032" +
      "\023.HeaterInfoResponse\"\000\0228\n\007TurnOff\022\026.Heat" +
      "erToUpdateRequest\032\023.HeaterInfoResponse\"\000" +
      "B\017\n\013com.HeatingP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Heater_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Heater_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Heater_descriptor,
        new java.lang.String[] { "DeviceId", "Location", "Status", "Temperature", });
    internal_static_HeaterStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeaterStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeaterStatusRequest_descriptor,
        new java.lang.String[] { "DeviceId", });
    internal_static_HeaterToUpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HeaterToUpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeaterToUpdateRequest_descriptor,
        new java.lang.String[] { "DeviceId", "Temp", });
    internal_static_HeaterInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_HeaterInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_HeaterInfoResponse_descriptor,
        new java.lang.String[] { "Heater", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
