// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heating.proto

package com.Heating;

public interface HeaterToUpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:HeaterToUpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 device_id = 1;</code>
   */
  int getDeviceId();

  /**
   * <code>int32 temp = 2;</code>
   */
  int getTemp();
}
