// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heating.proto

package com.Heating;

/**
 * Protobuf type {@code HeaterToUpdateRequest}
 */
public  final class HeaterToUpdateRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:HeaterToUpdateRequest)
    HeaterToUpdateRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use HeaterToUpdateRequest.newBuilder() to construct.
  private HeaterToUpdateRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HeaterToUpdateRequest() {
    deviceId_ = 0;
    temp_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private HeaterToUpdateRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            deviceId_ = input.readInt32();
            break;
          }
          case 16: {

            temp_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.Heating.Heating.internal_static_HeaterToUpdateRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.Heating.Heating.internal_static_HeaterToUpdateRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.Heating.HeaterToUpdateRequest.class, com.Heating.HeaterToUpdateRequest.Builder.class);
  }

  public static final int DEVICE_ID_FIELD_NUMBER = 1;
  private int deviceId_;
  /**
   * <code>int32 device_id = 1;</code>
   */
  public int getDeviceId() {
    return deviceId_;
  }

  public static final int TEMP_FIELD_NUMBER = 2;
  private int temp_;
  /**
   * <code>int32 temp = 2;</code>
   */
  public int getTemp() {
    return temp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (deviceId_ != 0) {
      output.writeInt32(1, deviceId_);
    }
    if (temp_ != 0) {
      output.writeInt32(2, temp_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (deviceId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, deviceId_);
    }
    if (temp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, temp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.Heating.HeaterToUpdateRequest)) {
      return super.equals(obj);
    }
    com.Heating.HeaterToUpdateRequest other = (com.Heating.HeaterToUpdateRequest) obj;

    boolean result = true;
    result = result && (getDeviceId()
        == other.getDeviceId());
    result = result && (getTemp()
        == other.getTemp());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEVICE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceId();
    hash = (37 * hash) + TEMP_FIELD_NUMBER;
    hash = (53 * hash) + getTemp();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.Heating.HeaterToUpdateRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.Heating.HeaterToUpdateRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.Heating.HeaterToUpdateRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.Heating.HeaterToUpdateRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.Heating.HeaterToUpdateRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.Heating.HeaterToUpdateRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.Heating.HeaterToUpdateRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.Heating.HeaterToUpdateRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.Heating.HeaterToUpdateRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.Heating.HeaterToUpdateRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.Heating.HeaterToUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.Heating.HeaterToUpdateRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.Heating.HeaterToUpdateRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code HeaterToUpdateRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:HeaterToUpdateRequest)
      com.Heating.HeaterToUpdateRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.Heating.Heating.internal_static_HeaterToUpdateRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.Heating.Heating.internal_static_HeaterToUpdateRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.Heating.HeaterToUpdateRequest.class, com.Heating.HeaterToUpdateRequest.Builder.class);
    }

    // Construct using com.Heating.HeaterToUpdateRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      deviceId_ = 0;

      temp_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.Heating.Heating.internal_static_HeaterToUpdateRequest_descriptor;
    }

    @java.lang.Override
    public com.Heating.HeaterToUpdateRequest getDefaultInstanceForType() {
      return com.Heating.HeaterToUpdateRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.Heating.HeaterToUpdateRequest build() {
      com.Heating.HeaterToUpdateRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.Heating.HeaterToUpdateRequest buildPartial() {
      com.Heating.HeaterToUpdateRequest result = new com.Heating.HeaterToUpdateRequest(this);
      result.deviceId_ = deviceId_;
      result.temp_ = temp_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.Heating.HeaterToUpdateRequest) {
        return mergeFrom((com.Heating.HeaterToUpdateRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.Heating.HeaterToUpdateRequest other) {
      if (other == com.Heating.HeaterToUpdateRequest.getDefaultInstance()) return this;
      if (other.getDeviceId() != 0) {
        setDeviceId(other.getDeviceId());
      }
      if (other.getTemp() != 0) {
        setTemp(other.getTemp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.Heating.HeaterToUpdateRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.Heating.HeaterToUpdateRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int deviceId_ ;
    /**
     * <code>int32 device_id = 1;</code>
     */
    public int getDeviceId() {
      return deviceId_;
    }
    /**
     * <code>int32 device_id = 1;</code>
     */
    public Builder setDeviceId(int value) {
      
      deviceId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 device_id = 1;</code>
     */
    public Builder clearDeviceId() {
      
      deviceId_ = 0;
      onChanged();
      return this;
    }

    private int temp_ ;
    /**
     * <code>int32 temp = 2;</code>
     */
    public int getTemp() {
      return temp_;
    }
    /**
     * <code>int32 temp = 2;</code>
     */
    public Builder setTemp(int value) {
      
      temp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 temp = 2;</code>
     */
    public Builder clearTemp() {
      
      temp_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:HeaterToUpdateRequest)
  }

  // @@protoc_insertion_point(class_scope:HeaterToUpdateRequest)
  private static final com.Heating.HeaterToUpdateRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.Heating.HeaterToUpdateRequest();
  }

  public static com.Heating.HeaterToUpdateRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HeaterToUpdateRequest>
      PARSER = new com.google.protobuf.AbstractParser<HeaterToUpdateRequest>() {
    @java.lang.Override
    public HeaterToUpdateRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new HeaterToUpdateRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HeaterToUpdateRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HeaterToUpdateRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.Heating.HeaterToUpdateRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

