// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Photo.proto

package com.Photo;

public interface LoadPhotoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:photo.LoadPhotoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes photo = 2;</code>
   */
  com.google.protobuf.ByteString getPhoto();
}
