// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Photo.proto

package com.Photo;

public interface Photo_InfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:photo.Photo_Info)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 device_id = 1;</code>
   */
  int getDeviceId();

  /**
   * <code>int32 photo_id = 2;</code>
   */
  int getPhotoId();

  /**
   * <code>bytes photo = 3;</code>
   */
  com.google.protobuf.ByteString getPhoto();
}
