// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Photo.proto

package com.Photo;

public interface PhotoViewResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:photo.PhotoViewResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool finished_upload = 1;</code>
   */
  boolean getFinishedUpload();
}
