// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Photo.proto

package com.Photo;

public final class Photo {
  private Photo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_photo_Photo_Info_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_photo_Photo_Info_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_photo_LoadPhotoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_photo_LoadPhotoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_photo_PhotoViewResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_photo_PhotoViewResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013Photo.proto\022\005photo\"@\n\nPhoto_Info\022\021\n\tde" +
      "vice_id\030\001 \001(\005\022\020\n\010photo_id\030\002 \001(\005\022\r\n\005photo" +
      "\030\003 \001(\014\"!\n\020LoadPhotoRequest\022\r\n\005photo\030\002 \001(" +
      "\014\",\n\021PhotoViewResponse\022\027\n\017finished_uploa" +
      "d\030\001 \001(\0102R\n\014PhotoService\022B\n\tViewPhoto\022\027.p" +
      "hoto.LoadPhotoRequest\032\030.photo.PhotoViewR" +
      "esponse\"\000(\001B\r\n\tcom.PhotoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_photo_Photo_Info_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_photo_Photo_Info_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_photo_Photo_Info_descriptor,
        new java.lang.String[] { "DeviceId", "PhotoId", "Photo", });
    internal_static_photo_LoadPhotoRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_photo_LoadPhotoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_photo_LoadPhotoRequest_descriptor,
        new java.lang.String[] { "Photo", });
    internal_static_photo_PhotoViewResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_photo_PhotoViewResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_photo_PhotoViewResponse_descriptor,
        new java.lang.String[] { "FinishedUpload", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
